server:
  port: 8083

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mariadb://mariadb:3306/hkt_shop
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin123}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1


management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true