spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mariadb://localhost:3306/hkt_shop
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: 20102004hinh@gmail.com
    password: ekvsgwrigrwecsgp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1

jwt:
  password:
    reset:
      secret: c8e09fddda9e192d16c485affabc61c9f4bca77a60c19d448f3a6e8475b9f0a4e0d1f69bca8d21f1123b8f0f8a0b8d12
      expiration: 900000

gemini:
  api:
    key: AIzaSyDU5B_gCzfGTlVLtlW-BOq3edCW4UnJ8eY

sepay:
  api-key: KH3T_SHOP_KEY
server:
  port: 8085