server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/products/**,/categories/**,/sizes/**,/size-details/**

        - id: wishlist-service-route
          uri: lb://wishlist-service
          predicates:
            - Path=/wishlists/**

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/users/**,/auth/**,/accounts/**

        - id: cart-service-route
          uri: lb://cart-service
          predicates:
            - Path=/carts/**,/cart-details/**

        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/orders/**,/order-details/**,/customers/**,/addresses/**,/customer-trading/**,/invoices/**,/api/v1/**
        - id: admin-service-route
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: chat-service-route
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1